export interface AccessoryItem {
  id: number;
  name: string;
  category: string;
  price: number;
  stock?: number;
  image?: string;
  subtitle?: string;
  description?: string;
  avg_rating?: number;
  review_count?: number;
  badge?: string;
  discount_percent?: number;
  total_sold?: number;
  views?: number;
  created_at?: string;
}

export const fallbackAccessories: AccessoryItem[] = [
  // ── Pots & Planters ────────────────────────────────────────────────────────
  {
    id: 101,
    name: "Minimalist Ceramic Planter",
    category: "Pots & Planters",
    price: 850,
    image: "/images/pot1.jpg",
    subtitle: "Handcrafted ceramic planter with drainage tray",
    description: "Premium smooth-finish ceramic pot with matching drainage saucer for moisture balance.",
    avg_rating: 4.9,
    review_count: 84,
    badge: "BESTSELLER",
    discount_percent: 20,
    stock: 25,
    total_sold: 140,
    views: 450,
  },
  {
    id: 102,
    name: "Terracotta Earth Breath Pot",
    category: "Pots & Planters",
    price: 650,
    image: "/images/pot2.jpg",
    subtitle: "Porous natural clay for optimum root airflow",
    description: "Classic terracotta planter baked at high heat for porous breathability and root health.",
    avg_rating: 4.8,
    review_count: 62,
    badge: "TRENDING",
    discount_percent: 15,
    stock: 30,
    total_sold: 95,
    views: 320,
  },
  {
    id: 103,
    name: "Marble Finish Statement Pot",
    category: "Pots & Planters",
    price: 1200,
    image: "/images/pot4.jpg",
    subtitle: "Luxury glazed indoor decorative centerpiece",
    description: "Modern marble-swirl ceramic pot that elevates indoor living rooms and offices.",
    avg_rating: 4.9,
    review_count: 53,
    badge: "FEATURED",
    discount_percent: 18,
    stock: 15,
    total_sold: 80,
    views: 290,
  },
  {
    id: 104,
    name: "Pastel Nordic Planter",
    category: "Pots & Planters",
    price: 799,
    image: "/images/pot3.webp",
    subtitle: "Contemporary indoor planter with base saucer",
    description: "Soft matte finish pot designed for succulents, snake plants, and desktop foliage.",
    avg_rating: 4.7,
    review_count: 41,
    badge: "POPULAR",
    discount_percent: 12,
    stock: 20,
    total_sold: 65,
    views: 210,
  },

  // ── Soil & Media ───────────────────────────────────────────────────────────
  {
    id: 105,
    name: "Organic Indoor Potting Mix (5kg)",
    category: "Soil & Media",
    price: 450,
    image: "/images/best-soil-for-indoor-plants-1000x667-62c2fde2d71ae_n.webp",
    subtitle: "Enriched nutrient mix with perlite & coco peat",
    description: "Sterilized organic potting substrate formulated to prevent root rot and promote growth.",
    avg_rating: 4.9,
    review_count: 128,
    badge: "BESTSELLER",
    discount_percent: 15,
    stock: 50,
    total_sold: 210,
    views: 600,
  },
  {
    id: 113,
    name: "Pure Washed Coco Peat Block (650g)",
    category: "Soil & Media",
    price: 180,
    image: "/images/best-soil-for-indoor-plants-1000x667-62c2fde2d71ae_n.webp",
    subtitle: "Expands up to 9 liters of fluffy growing substrate",
    description: "High moisture-retentive base medium for seed germination, potting blends, and cuttings.",
    avg_rating: 4.8,
    review_count: 112,
    badge: "TRENDING",
    discount_percent: 10,
    stock: 60,
    total_sold: 230,
    views: 520,
  },
  {
    id: 116,
    name: "Perlite Aeration Substrate (2L)",
    category: "Soil & Media",
    price: 240,
    image: "/images/best-soil-for-indoor-plants-1000x667-62c2fde2d71ae_n.webp",
    subtitle: "Sterilized volcanic glass for porous soil aeration",
    description: "Prevents soil compaction and improves oxygen circulation around delicate root systems.",
    avg_rating: 4.9,
    review_count: 76,
    badge: "POPULAR",
    discount_percent: 10,
    stock: 45,
    total_sold: 180,
    views: 410,
  },

  // ── Fertilisers & Plant Food ───────────────────────────────────────────────
  {
    id: 109,
    name: "Indoor Plant Food & Fertilizer Drops",
    category: "Fertilisers",
    price: 320,
    image: "/images/best-soil-for-indoor-plants-1000x667-62c2fde2d71ae_n.webp",
    subtitle: "Liquid concentrated nutrient blend for rapid leaf growth",
    description: "Gentle micronutrient formula to boost leaf shine, root strength, and bloom vigor.",
    avg_rating: 4.8,
    review_count: 81,
    badge: "ESSENTIAL",
    discount_percent: 10,
    stock: 40,
    total_sold: 160,
    views: 430,
  },
  {
    id: 122,
    name: "Organic Vermicompost Fertilizer (5kg)",
    category: "Fertilisers",
    price: 390,
    image: "/images/best-soil-for-indoor-plants-1000x667-62c2fde2d71ae_n.webp",
    subtitle: "Nutrient-rich natural earthworm castings",
    description: "Odorless bio-fertilizer packed with beneficial microbes, nitrogen, and essential trace minerals.",
    avg_rating: 4.9,
    review_count: 118,
    badge: "ORGANIC",
    discount_percent: 15,
    stock: 45,
    total_sold: 215,
    views: 570,
  },

  // ── Seeds (Ugaoo Inspired) ────────────────────────────────────────────────
  {
    id: 130,
    name: "Heirloom Cherry Tomato Seeds (50 Seeds)",
    category: "Seeds",
    price: 180,
    image: "/images/categories/seeds.webp",
    subtitle: "High-yield sweet balcony cherry tomatoes",
    description: "Prolific fruiting variety ideal for sunny balconies, terrace gardens, and window boxes.",
    avg_rating: 4.8,
    review_count: 67,
    badge: "TOP SELLER",
    discount_percent: 15,
    stock: 40,
    total_sold: 145,
    views: 380,
  },
  {
    id: 131,
    name: "Holy Basil & Italian Sweet Basil Combo Seeds",
    category: "Seeds",
    price: 160,
    image: "/images/categories/seeds.webp",
    subtitle: "Aromatic dual-herb packet for tea and culinary kitchens",
    description: "Non-GMO organic culinary and medicinal basil seeds with over 90% germination rate.",
    avg_rating: 4.9,
    review_count: 94,
    badge: "ORGANIC",
    discount_percent: 10,
    stock: 50,
    total_sold: 210,
    views: 450,
  },
  {
    id: 132,
    name: "Dwarf Golden Sunflower Seeds Pack",
    category: "Seeds",
    price: 199,
    image: "/images/categories/seeds.webp",
    subtitle: "Compact vibrant yellow blooms for indoor planters",
    description: "Cheerful potted dwarf sunflowers that bloom within 60 days of planting.",
    avg_rating: 4.7,
    review_count: 42,
    badge: "POPULAR",
    discount_percent: 20,
    stock: 30,
    total_sold: 88,
    views: 290,
  },
  {
    id: 133,
    name: "Superfood Microgreens Germination Kit & Seeds",
    category: "Seeds",
    price: 350,
    image: "/images/categories/seeds.webp",
    subtitle: "Radish, mustard, and broccoli nutrient microgreens",
    description: "Grow nutrient-dense greens right on your kitchen counter in just 7 to 10 days.",
    avg_rating: 4.9,
    review_count: 55,
    badge: "BESTSELLER",
    discount_percent: 12,
    stock: 25,
    total_sold: 120,
    views: 340,
  },

  // ── Garden Tools ──────────────────────────────────────────────────────────
  {
    id: 107,
    name: "Heavy-Duty Garden Trowel",
    category: "Garden Tools",
    price: 380,
    image: "/images/sovel.webp",
    subtitle: "Rust-resistant stainless steel hand shovel",
    description: "Durable gardening hand shovel with ergonomic wooden grip for repotting and soil aeration.",
    avg_rating: 4.8,
    review_count: 73,
    badge: "FEATURED",
    discount_percent: 15,
    stock: 35,
    total_sold: 70,
    views: 240,
  },
  {
    id: 120,
    name: "Soil Moisture & Light Meter (3-in-1)",
    category: "Garden Tools",
    price: 680,
    image: "/images/can.jpg",
    subtitle: "Battery-free sensor for moisture, pH, and light",
    description: "Takes the guesswork out of watering by showing exactly how wet the soil is deep inside the root zone.",
    avg_rating: 4.8,
    review_count: 104,
    badge: "RECOMMENDED",
    discount_percent: 20,
    stock: 22,
    total_sold: 140,
    views: 490,
  },
  {
    id: 123,
    name: "Soft-Grip Soil Hand Cultivator",
    category: "Garden Tools",
    price: 340,
    image: "/images/sovel.webp",
    subtitle: "Three-prong claw for soil loosening and aerating",
    description: "Ergonomic handheld cultivator to break soil crusts and mix in fertilizers without damaging roots.",
    avg_rating: 4.8,
    review_count: 52,
    badge: "FEATURED",
    discount_percent: 12,
    stock: 30,
    total_sold: 78,
    views: 230,
  },

  // ── Watering Solutions ────────────────────────────────────────────────────
  {
    id: 106,
    name: "Long-Spout Precision Watering Can",
    category: "Watering",
    price: 650,
    image: "/images/can.jpg",
    subtitle: "Ergonomic stainless steel precision spout",
    description: "Narrow spout directs water straight to soil without splashing leaves or furniture.",
    avg_rating: 4.8,
    review_count: 95,
    badge: "BESTSELLER",
    discount_percent: 20,
    stock: 22,
    total_sold: 110,
    views: 390,
  },
  {
    id: 115,
    name: "Fine Mist Brass Plant Spritzer",
    category: "Watering",
    price: 490,
    image: "/images/can.jpg",
    subtitle: "Vintage brass mist sprayer for humid tropicals",
    description: "Gentle ambient mist sprayer ideal for calatheas, ferns, monsteras, and moss poles.",
    avg_rating: 4.7,
    review_count: 54,
    badge: "FEATURED",
    discount_percent: 18,
    stock: 25,
    total_sold: 92,
    views: 280,
  },
  {
    id: 124,
    name: "Pure Copper Plant Watering Jug",
    category: "Watering",
    price: 1450,
    image: "/images/can.jpg",
    subtitle: "Handcrafted pure copper watering pitcher",
    description: "Naturally antimicrobial copper water jug that doubles as an elegant countertop display piece.",
    avg_rating: 4.9,
    review_count: 41,
    badge: "LUXURY",
    discount_percent: 15,
    stock: 12,
    total_sold: 45,
    views: 310,
  },

  // ── Pest Control & Plant Care ─────────────────────────────────────────────
  {
    id: 134,
    name: "Organic Cold-Pressed Neem Oil Spray (500ml)",
    category: "Plant Care",
    price: 450,
    image: "/images/categories/care.webp",
    subtitle: "Pure horticultural neem oil defense for mealybugs & gnats",
    description: "Ready-to-use organic foliar spray that eliminates scale, aphids, spider mites, and leaf spot safely.",
    avg_rating: 4.9,
    review_count: 142,
    badge: "MUST-HAVE",
    discount_percent: 15,
    stock: 35,
    total_sold: 260,
    views: 680,
  },
  {
    id: 135,
    name: "Yellow Sticky Insect Traps (Pack of 10)",
    category: "Plant Care",
    price: 220,
    image: "/images/categories/care.webp",
    subtitle: "Pesticide-free traps for fungus gnats & thrips",
    description: "Waterproof bright yellow adhesive sheets that trap flying soil pests before they multiply.",
    avg_rating: 4.8,
    review_count: 89,
    badge: "EFFECTIVE",
    discount_percent: 10,
    stock: 50,
    total_sold: 190,
    views: 420,
  },

  // ── Gardening Decor (Ugaoo Inspired) ──────────────────────────────────────
  {
    id: 117,
    name: "Macrame Plant Hanger (100% Cotton)",
    category: "Gardening Decor",
    price: 420,
    image: "/images/categories/decor.webp",
    subtitle: "Hand-knotted boho hanging rope for 6-10 inch pots",
    description: "Durable woven cotton hanging sling to display cascading pothos, philodendrons, and string of pearls.",
    avg_rating: 4.8,
    review_count: 63,
    badge: "BESTSELLER",
    discount_percent: 15,
    stock: 30,
    total_sold: 115,
    views: 340,
  },
  {
    id: 118,
    name: "Moss Pole Climbing Support (3ft)",
    category: "Gardening Decor",
    price: 360,
    image: "/images/sovel.webp",
    subtitle: "Natural coco coir stake for aerial root climbers",
    description: "Encourages larger leaf fenestration on Monstera deliciosa, Syngoniums, and climbing pothos.",
    avg_rating: 4.9,
    review_count: 91,
    badge: "ESSENTIAL",
    discount_percent: 12,
    stock: 40,
    total_sold: 175,
    views: 460,
  },
  {
    id: 121,
    name: "Polished River Pebbles (1kg)",
    category: "Gardening Decor",
    price: 220,
    image: "/images/categories/decor.webp",
    subtitle: "Natural smooth decorative mulch pebbles",
    description: "Retains topsoil moisture, prevents fungus gnats, and adds a neat spa finish to potted plants.",
    avg_rating: 4.6,
    review_count: 48,
    badge: "DECOR",
    discount_percent: 10,
    stock: 50,
    total_sold: 95,
    views: 260,
  },
  {
    id: 136,
    name: "Miniature Fairy Garden Figurines (Set of 4)",
    category: "Gardening Decor",
    price: 340,
    image: "/images/categories/decor.webp",
    subtitle: "Cute resin mushrooms and woodland creatures",
    description: "Whimsical waterproof figurines that turn potted plants and bonsai containers into mini landscapes.",
    avg_rating: 4.9,
    review_count: 36,
    badge: "CUTE",
    discount_percent: 15,
    stock: 25,
    total_sold: 72,
    views: 210,
  },
];
