export interface SeedItem {
  id: number;
  name: string;
  category: "Vegetable Seeds" | "Flower Seeds" | "Herb Seeds" | "Microgreens" | "Fruit & Exotic Seeds" | "Combo Kits";
  scientific_name?: string;
  season: "All Season" | "Summer" | "Winter" | "Monsoon" | "Spring";
  germination_days: string;
  harvest_days: string;
  germination_rate: string;
  sunlight: "Full Sun" | "Partial Shade" | "Bright Indirect" | "Indoor Windowsill";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  price: number;
  discount_percent: number;
  stock: number;
  image: string;
  subtitle: string;
  description: string;
  avg_rating: number;
  review_count: number;
  badge?: string;
  total_sold?: number;
  views?: number;
  is_active?: boolean;
}

export const fallbackSeeds: SeedItem[] = [
  {
    id: 301,
    name: "Heirloom Cherry Tomato Seeds (50 Seeds)",
    category: "Vegetable Seeds",
    scientific_name: "Solanum lycopersicum var. cerasiforme",
    season: "Spring",
    germination_days: "5 - 8 Days",
    harvest_days: "60 - 75 Days",
    germination_rate: "92%",
    sunlight: "Full Sun",
    difficulty: "Beginner",
    price: 180,
    discount_percent: 15,
    stock: 65,
    image: "/images/seeds_tomato.jpg",
    subtitle: "High-yield sweet balcony ruby cherry tomatoes",
    description: "Certified open-pollinated heirloom seeds producing clusters of ultra-sweet, bite-sized cherry tomatoes. Thrives wonderfully in terracotta pots on balconies and sunny terraces across Nepal.",
    avg_rating: 4.9,
    review_count: 88,
    badge: "HEIRLOOM",
    total_sold: 215,
    views: 640,
    is_active: true,
  },
  {
    id: 302,
    name: "Italian Sweet Basil Seeds (100 Seeds)",
    category: "Herb Seeds",
    scientific_name: "Ocimum basilicum",
    season: "All Season",
    germination_days: "4 - 7 Days",
    harvest_days: "30 - 45 Days",
    germination_rate: "95%",
    sunlight: "Bright Indirect",
    difficulty: "Beginner",
    price: 160,
    discount_percent: 10,
    stock: 90,
    image: "/images/categories/seeds.webp",
    subtitle: "Aromatic culinary herb for pesto and salads",
    description: "Fast-sprouting aromatic culinary herb seeds with luscious, fragrant leaves. Ideal for sunny kitchen windowsills, companion vegetable gardening, and fresh pesto.",
    avg_rating: 4.8,
    review_count: 94,
    badge: "BESTSELLER",
    total_sold: 310,
    views: 720,
    is_active: true,
  },
  {
    id: 303,
    name: "Dwarf Golden Sunflower Seeds (30 Seeds)",
    category: "Flower Seeds",
    scientific_name: "Helianthus annuus nano",
    season: "Summer",
    germination_days: "6 - 10 Days",
    harvest_days: "55 - 65 Days",
    germination_rate: "89%",
    sunlight: "Full Sun",
    difficulty: "Beginner",
    price: 199,
    discount_percent: 20,
    stock: 45,
    image: "/images/categories/seeds.webp",
    subtitle: "Vibrant yellow patio blooms for potted gardens",
    description: "Compact miniature sunflowers reaching 30-40cm height. Produces radiant golden blooms that attract honeybees and brighten apartment balconies with cheerful color.",
    avg_rating: 4.7,
    review_count: 52,
    badge: "POPULAR",
    total_sold: 140,
    views: 480,
    is_active: true,
  },
  {
    id: 304,
    name: "Superfood Microgreens Germination Kit (3 Varieties)",
    category: "Microgreens",
    scientific_name: "Brassica oleracea & Raphanus sativus",
    season: "All Season",
    germination_days: "2 - 3 Days",
    harvest_days: "7 - 10 Days",
    germination_rate: "98%",
    sunlight: "Indoor Windowsill",
    difficulty: "Beginner",
    price: 350,
    discount_percent: 12,
    stock: 35,
    image: "/images/categories/seeds.webp",
    subtitle: "Broccoli, radish, and mustard nutrient powerhouses",
    description: "Everything you need to harvest fresh gourmet superfoods right on your kitchen counter. Loaded with 40x more concentrated vitamins and minerals than mature plants.",
    avg_rating: 4.9,
    review_count: 67,
    badge: "SUPERFOOD",
    total_sold: 195,
    views: 530,
    is_active: true,
  },
  {
    id: 305,
    name: "Fiery Akabare & Bird's Eye Green Chili Seeds (80 Seeds)",
    category: "Vegetable Seeds",
    scientific_name: "Capsicum frutescens",
    season: "Monsoon",
    germination_days: "8 - 14 Days",
    harvest_days: "70 - 85 Days",
    germination_rate: "90%",
    sunlight: "Full Sun",
    difficulty: "Beginner",
    price: 150,
    discount_percent: 15,
    stock: 80,
    image: "/images/categories/seeds.webp",
    subtitle: "High-spice traditional Nepali chili seeds",
    description: "Prolific, heat-loving spicy chili seeds bred for Nepali conditions. Plants yield hundreds of vibrant, aromatic green and fiery red chilies per season.",
    avg_rating: 4.8,
    review_count: 76,
    badge: "NEPALI SPECIAL",
    total_sold: 280,
    views: 610,
    is_active: true,
  },
  {
    id: 306,
    name: "Golden African Marigold Seeds (100 Seeds)",
    category: "Flower Seeds",
    scientific_name: "Tagetes erecta",
    season: "Winter",
    germination_days: "4 - 6 Days",
    harvest_days: "45 - 55 Days",
    germination_rate: "94%",
    sunlight: "Full Sun",
    difficulty: "Beginner",
    price: 140,
    discount_percent: 10,
    stock: 110,
    image: "/images/categories/seeds.webp",
    subtitle: "Tihar festive rich orange and gold blooms",
    description: "Premium large-headed marigold seeds perfect for autumn and festive Tihar gardens. Natural pest-repelling qualities make it an essential companion for home vegetables.",
    avg_rating: 4.9,
    review_count: 112,
    badge: "FESTIVE FAVORITE",
    total_sold: 430,
    views: 890,
    is_active: true,
  },
  {
    id: 307,
    name: "Crisp Green Kitchen Coriander (Dhaniya) Seeds (200 Seeds)",
    category: "Herb Seeds",
    scientific_name: "Coriandrum sativum",
    season: "Winter",
    germination_days: "7 - 12 Days",
    harvest_days: "35 - 45 Days",
    germination_rate: "91%",
    sunlight: "Partial Shade",
    difficulty: "Beginner",
    price: 120,
    discount_percent: 10,
    stock: 130,
    image: "/images/categories/seeds.webp",
    subtitle: "Essential culinary fresh coriander leaves",
    description: "Multi-cut coriander seeds that yield tender, deeply aromatic leaves. Cut and come again multiple times throughout the cooler autumn and winter months.",
    avg_rating: 4.8,
    review_count: 65,
    badge: "KITCHEN ESSENTIAL",
    total_sold: 350,
    views: 590,
    is_active: true,
  },
  {
    id: 308,
    name: "French Blue Lavender Seeds (50 Seeds)",
    category: "Flower Seeds",
    scientific_name: "Lavandula angustifolia",
    season: "Spring",
    germination_days: "14 - 21 Days",
    harvest_days: "90 - 110 Days",
    germination_rate: "82%",
    sunlight: "Full Sun",
    difficulty: "Intermediate",
    price: 260,
    discount_percent: 15,
    stock: 28,
    image: "/images/categories/seeds.webp",
    subtitle: "Calming fragrant purple spikes for sunny spots",
    description: "Classic culinary and ornamental perennial lavender. Infuses balcony breezes with soothing fragrance and natural therapeutic qualities.",
    avg_rating: 4.6,
    review_count: 38,
    badge: "AROMATIC",
    total_sold: 95,
    views: 380,
    is_active: true,
  },
  {
    id: 309,
    name: "Tender Baby Spinach (Palak) Seeds (150 Seeds)",
    category: "Vegetable Seeds",
    scientific_name: "Spinacia oleracea",
    season: "Winter",
    germination_days: "5 - 8 Days",
    harvest_days: "30 - 40 Days",
    germination_rate: "93%",
    sunlight: "Partial Shade",
    difficulty: "Beginner",
    price: 135,
    discount_percent: 10,
    stock: 95,
    image: "/images/categories/seeds.webp",
    subtitle: "Fast-growing iron-rich leafy greens",
    description: "Non-bitter smooth baby spinach seeds suited for shallow pots and balcony planters. Rich in iron, zinc, and crisp earthy flavor for daily meals.",
    avg_rating: 4.8,
    review_count: 57,
    badge: "EASY TO GROW",
    total_sold: 210,
    views: 440,
    is_active: true,
  },
  {
    id: 310,
    name: "Sweet Alpine Red Strawberry Seeds (40 Seeds)",
    category: "Fruit & Exotic Seeds",
    scientific_name: "Fragaria vesca",
    season: "Spring",
    germination_days: "15 - 25 Days",
    harvest_days: "90 - 120 Days",
    germination_rate: "80%",
    sunlight: "Full Sun",
    difficulty: "Intermediate",
    price: 280,
    discount_percent: 20,
    stock: 22,
    image: "/images/categories/seeds.webp",
    subtitle: "Intensely sweet wild balcony strawberries",
    description: "Ever-bearing compact alpine strawberry plants with sweet ruby berries all summer long. Perfect for hanging baskets and elevated planters.",
    avg_rating: 4.7,
    review_count: 29,
    badge: "EXOTIC FRUIT",
    total_sold: 80,
    views: 390,
    is_active: true,
  },
  {
    id: 311,
    name: "Nepal Balcony Kitchen Garden 5-in-1 Seed Kit",
    category: "Combo Kits",
    scientific_name: "Curated Variety Pack",
    season: "All Season",
    germination_days: "4 - 10 Days",
    harvest_days: "30 - 75 Days",
    germination_rate: "94%",
    sunlight: "Full Sun",
    difficulty: "Beginner",
    price: 650,
    discount_percent: 25,
    stock: 30,
    image: "/images/categories/seeds.webp",
    subtitle: "Complete home starter kit: Tomato, Basil, Chili, Coriander, Spinach",
    description: "The ultimate starter pack for aspiring apartment gardeners. Includes 5 popular high-germination seed packets, 10 biodegradable coir seedling pods, and an illustrated Kathmandu sowing calendar.",
    avg_rating: 5.0,
    review_count: 46,
    badge: "VALUE PACK",
    total_sold: 175,
    views: 520,
    is_active: true,
  },
  {
    id: 312,
    name: "Zinnia Elegans Colorful Bloom Mix Seeds (75 Seeds)",
    category: "Flower Seeds",
    scientific_name: "Zinnia elegans",
    season: "Summer",
    germination_days: "4 - 7 Days",
    harvest_days: "50 - 60 Days",
    germination_rate: "92%",
    sunlight: "Full Sun",
    difficulty: "Beginner",
    price: 175,
    discount_percent: 15,
    stock: 55,
    image: "/images/categories/seeds.webp",
    subtitle: "Dahlia-flowered butterfly magnets in mixed hues",
    description: "Stunning double and semi-double blossoms in pink, orange, scarlet, and purple. Long vase life and heat tolerance make Zinnias a summertime standout.",
    avg_rating: 4.8,
    review_count: 34,
    badge: "BUTTERFLY MAGNET",
    total_sold: 110,
    views: 310,
    is_active: true,
  },
];
