<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Plant;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PlantSeeder extends Seeder
{
    public function run(): void
    {
        $plants = [
            [
                'name' => 'Monstera Deliciosa',
                'scientific_name' => 'Monstera deliciosa',
                'category' => 'Indoor Plants',
                'size' => 'Medium',
                'difficulty' => 'easy',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '18-28°C',
                'humidity' => '60-80%',
                'rooms' => ['living-room', 'bedroom'],
                'quantity_categories' => ['single', 'pair'],
                'fertilizer' => 'Balanced liquid fertilizer once a month during spring and summer.',
                'soil' => 'Chunky aroid mix with pine bark, perlite, and coconut coir.',
                'description' => 'The iconic Swiss Cheese plant famous for its lush perforated fenestrations. Perfect statement foliage for contemporary living rooms.',
                'price' => 1450.00,
                'stock' => 25,
                'image' => '/images/mos.jpg',
                'is_active' => true,
                'views' => 420,
                'total_sold' => 28,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Snake Plant Laurentii',
                'scientific_name' => 'Sansevieria trifasciata',
                'category' => 'Air Purifying',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => 'low-light',
                'water' => 'low',
                'temperature' => '15-30°C',
                'humidity' => '30-50%',
                'rooms' => ['bedroom', 'office'],
                'quantity_categories' => ['single', 'set-of-3'],
                'fertilizer' => 'Mild organic fertilizer once every two months.',
                'soil' => 'Fast-draining cactus and succulent mix.',
                'description' => 'Virtually indestructible air purifier that releases fresh oxygen during the night. Tolerates low light and occasional neglect.',
                'price' => 850.00,
                'stock' => 40,
                'image' => '/images/snake.jpg',
                'is_active' => true,
                'views' => 680,
                'total_sold' => 45,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Rubber Tree Burgundy',
                'scientific_name' => 'Ficus elastica',
                'category' => 'Indoor Plants',
                'size' => 'Large',
                'difficulty' => 'easy',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '18-26°C',
                'humidity' => '50-70%',
                'rooms' => ['living-room', 'hallway'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Liquid houseplant fertilizer every 3 weeks in growing season.',
                'soil' => 'Well-draining potting soil with pumice.',
                'description' => 'Dramatic glossy deep-burgundy leaves that add architectural presence to any bright indoor space.',
                'price' => 1200.00,
                'stock' => 18,
                'image' => '/images/rubber.jpg',
                'is_active' => true,
                'views' => 350,
                'total_sold' => 19,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Organic Aloe Vera',
                'scientific_name' => 'Aloe barbadensis',
                'category' => 'Succulents',
                'size' => 'Small',
                'difficulty' => 'beginner',
                'light' => 'direct-sun',
                'water' => 'low',
                'temperature' => '15-32°C',
                'humidity' => '20-40%',
                'rooms' => ['kitchen', 'balcony'],
                'quantity_categories' => ['single', 'pair'],
                'fertilizer' => 'Diluted succulent fertilizer once in spring.',
                'soil' => 'Gritty sand and perlite mix.',
                'description' => 'Healing succulent known for its soothing gel, cooling properties, and tolerance to hot sunny windowsills.',
                'price' => 450.00,
                'stock' => 50,
                'image' => '/images/alovera.jpg',
                'is_active' => true,
                'views' => 290,
                'total_sold' => 32,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Peace Lily Sensation',
                'scientific_name' => 'Spathiphyllum wallisii',
                'category' => 'Flowering',
                'size' => 'Medium',
                'difficulty' => 'easy',
                'light' => 'medium-indirect',
                'water' => 'high',
                'temperature' => '18-25°C',
                'humidity' => '60-80%',
                'rooms' => ['bedroom', 'bathroom'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Bloom booster liquid feed monthly.',
                'soil' => 'Moisture-retentive peat and perlite potting compost.',
                'description' => 'Elegant white floral spathes rising gracefully above deep-green emerald leaves. Tells you clearly when it needs water by drooping gently.',
                'price' => 950.00,
                'stock' => 30,
                'image' => '/images/lily.jpg',
                'is_active' => true,
                'views' => 510,
                'total_sold' => 38,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Variegated Spider Plant',
                'scientific_name' => 'Chlorophytum comosum',
                'category' => 'Air Purifying',
                'size' => 'Small',
                'difficulty' => 'beginner',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '15-28°C',
                'humidity' => '40-60%',
                'rooms' => ['living-room', 'bedroom', 'study'],
                'quantity_categories' => ['single', 'hanging-basket'],
                'fertilizer' => 'All-purpose houseplant feed bi-weekly.',
                'soil' => 'Standard fertile potting soil.',
                'description' => 'Charming hanging plant producing arching ribbons of green and cream, frequently cascading baby spiderettes.',
                'price' => 550.00,
                'stock' => 35,
                'image' => '/images/spider.jpg',
                'is_active' => true,
                'views' => 310,
                'total_sold' => 22,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Golden Pothos Devil\'s Ivy',
                'scientific_name' => 'Epipremnum aureum',
                'category' => 'Air Purifying',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => 'low-light',
                'water' => 'low',
                'temperature' => '15-30°C',
                'humidity' => '50-80%',
                'rooms' => ['bedroom', 'bathroom', 'living-room', 'office'],
                'quantity_categories' => ['single', 'hanging-basket'],
                'fertilizer' => 'Balanced houseplant fertilizer once a month.',
                'soil' => 'Rich, well-aerated potting soil.',
                'description' => 'Unstoppable trailing vine with golden-splashed emerald heart leaves. Extremely forgiving and adapts to low light or humid bathrooms.',
                'price' => 600.00,
                'stock' => 50,
                'image' => '/images/pothos.jpg',
                'is_active' => true,
                'views' => 490,
                'total_sold' => 41,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Fiddle Leaf Fig Tree',
                'scientific_name' => 'Ficus lyrata',
                'category' => 'Indoor Plants',
                'size' => 'Large',
                'difficulty' => 'intermediate',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '18-26°C',
                'humidity' => '50-70%',
                'rooms' => ['living-room', 'office'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'High-nitrogen fertilizer monthly in spring and summer.',
                'soil' => 'Chunky well-draining potting medium.',
                'description' => 'Architectural centerpiece boasting giant violin-shaped scalloped leaves. Adds high-fashion interior designer luxury to any bright living space.',
                'price' => 2200.00,
                'stock' => 15,
                'image' => '/images/fiddle.jpg',
                'is_active' => true,
                'views' => 620,
                'total_sold' => 18,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Areca Butterfly Palm',
                'scientific_name' => 'Dypsis lutescens',
                'category' => 'Indoor Plants',
                'size' => 'Large',
                'difficulty' => 'easy',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '18-28°C',
                'humidity' => '55-75%',
                'rooms' => ['living-room', 'balcony'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Liquid palm fertilizer every 4 weeks.',
                'soil' => 'Rich loam with perlite and sand for drainage.',
                'description' => 'Graceful feathery palm fronds creating an instant tropical resort ambiance. Outstanding natural humidifier and air purifier.',
                'price' => 1750.00,
                'stock' => 20,
                'image' => '/images/palm.jpg',
                'is_active' => true,
                'views' => 540,
                'total_sold' => 26,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'ZZ Plant Fortune Gem',
                'scientific_name' => 'Zamioculcas zamiifolia',
                'category' => 'Air Purifying',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => 'low-light',
                'water' => 'low',
                'temperature' => '15-32°C',
                'humidity' => '30-60%',
                'rooms' => ['bedroom', 'office', 'bathroom'],
                'quantity_categories' => ['single', 'pair'],
                'fertilizer' => 'Quarter-strength houseplant food in summer.',
                'soil' => 'Cactus and succulent potting mix.',
                'description' => 'Ultra-glossy zigzag stems with mirror-shine waxy leaflets. Stores water in subterranean rhizomes, surviving weeks of low light and zero attention.',
                'price' => 950.00,
                'stock' => 35,
                'image' => '/images/zzplant.jpg',
                'is_active' => true,
                'views' => 430,
                'total_sold' => 33,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Lucky Jade Money Tree',
                'scientific_name' => 'Crassula ovata',
                'category' => 'Succulents',
                'size' => 'Small',
                'difficulty' => 'beginner',
                'light' => 'direct-sun',
                'water' => 'low',
                'temperature' => '12-30°C',
                'humidity' => '20-45%',
                'rooms' => ['balcony', 'kitchen', 'office'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Succulent food twice per year.',
                'soil' => 'Gritty bonsai or succulent blend.',
                'description' => 'Symbol of prosperity and positive chi with plump miniature jade-green oval leaves on miniature tree-like woody stems.',
                'price' => 550.00,
                'stock' => 45,
                'image' => '/images/jade.jpg',
                'is_active' => true,
                'views' => 380,
                'total_sold' => 29,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'English Ivy Glacier',
                'scientific_name' => 'Hedera helix',
                'category' => 'Indoor Plants',
                'size' => 'Small',
                'difficulty' => 'easy',
                'light' => 'medium-indirect',
                'water' => 'moderate',
                'temperature' => '10-24°C',
                'humidity' => '50-70%',
                'rooms' => ['living-room', 'bedroom', 'bathroom'],
                'quantity_categories' => ['single', 'hanging-basket'],
                'fertilizer' => 'Foliage fertilizer monthly.',
                'soil' => 'Standard organic potting compost.',
                'description' => 'Cascading timeless English ivy with variegated triangular lobes. Excellent for hanging planters, bookshelves, and desktop corners.',
                'price' => 480.00,
                'stock' => 40,
                'image' => '/images/about-plants.jpg',
                'is_active' => true,
                'views' => 270,
                'total_sold' => 19,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Boston Sword Fern',
                'scientific_name' => 'Nephrolepis exaltata',
                'category' => 'Indoor Plants',
                'size' => 'Medium',
                'difficulty' => 'easy',
                'light' => 'indirect-light',
                'water' => 'high',
                'temperature' => '16-26°C',
                'humidity' => '65-85%',
                'rooms' => ['bathroom', 'living-room', 'balcony'],
                'quantity_categories' => ['single', 'hanging-basket'],
                'fertilizer' => 'Diluted liquid fern feed every 3 weeks.',
                'soil' => 'Rich peat-moss and humus mix.',
                'description' => 'Abundant lush emerald fronds that billow gracefully in hanging baskets. Passionate lover of bathroom humidity and ambient moisture.',
                'price' => 750.00,
                'stock' => 30,
                'image' => '/images/winter-garden.png',
                'is_active' => true,
                'views' => 360,
                'total_sold' => 21,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Calathea Medallion Prayer Plant',
                'scientific_name' => 'Calathea roseopicta',
                'category' => 'Indoor Plants',
                'size' => 'Medium',
                'difficulty' => 'intermediate',
                'light' => 'medium-indirect',
                'water' => 'moderate',
                'temperature' => '18-27°C',
                'humidity' => '60-80%',
                'rooms' => ['bedroom', 'living-room', 'bathroom'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Diluted balanced houseplant fertilizer monthly.',
                'soil' => 'Moist, rich, well-aerated potting soil with perlite.',
                'description' => 'Stunning medallion-patterned round leaves with rich royal purple undersides that fold upward at night like hands in prayer.',
                'price' => 880.00,
                'stock' => 25,
                'image' => '/images/indoor-garden.jpg',
                'is_active' => true,
                'views' => 310,
                'total_sold' => 17,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Desert Saguaro Cactus',
                'scientific_name' => 'Carnegiea gigantea',
                'category' => 'Succulents',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => 'direct-sun',
                'water' => 'low',
                'temperature' => '12-35°C',
                'humidity' => '15-35%',
                'rooms' => ['balcony', 'living-room', 'office'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Cactus fertilizer twice per year during summer.',
                'soil' => 'Extra gritty coarse sand and volcanic pumice.',
                'description' => 'Iconic multi-armed columnar desert cactus. Thrives on sun-drenched balconies and requires minimal watering.',
                'price' => 650.00,
                'stock' => 30,
                'image' => '/images/alovera.jpg',
                'is_active' => true,
                'views' => 280,
                'total_sold' => 14,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Red Flamingo Anthurium',
                'scientific_name' => 'Anthurium andraeanum',
                'category' => 'Flowering',
                'size' => 'Medium',
                'difficulty' => 'intermediate',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '18-28°C',
                'humidity' => '60-80%',
                'rooms' => ['living-room', 'bedroom', 'office'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'High-phosphorus bloom liquid fertilizer every 3 weeks.',
                'soil' => 'Coarse aroid mix with orchid bark and perlite.',
                'description' => 'Exotic heart-shaped waxy blooms in brilliant lacquer scarlet red with a bright yellow spadix, lasting months in full glory.',
                'price' => 1100.00,
                'stock' => 20,
                'image' => '/images/lily.jpg',
                'is_active' => true,
                'views' => 390,
                'total_sold' => 22,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Dragon Tree Marginata',
                'scientific_name' => 'Dracaena marginata',
                'category' => 'Air Purifying',
                'size' => 'Large',
                'difficulty' => 'easy',
                'light' => 'bright-indirect',
                'water' => 'low',
                'temperature' => '16-28°C',
                'humidity' => '40-60%',
                'rooms' => ['living-room', 'office', 'bedroom'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Light liquid feeding twice in spring and summer.',
                'soil' => 'Loose well-draining loamy potting mix.',
                'description' => 'Slender curving woody canes crowned with fountain explosions of narrow arching leaves edged in dramatic ruby crimson.',
                'price' => 1350.00,
                'stock' => 18,
                'image' => '/images/palm.jpg',
                'is_active' => true,
                'views' => 340,
                'total_sold' => 16,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Ginseng Ficus Indoor Bonsai',
                'scientific_name' => 'Ficus microcarpa',
                'category' => 'Indoor Plants',
                'size' => 'Medium',
                'difficulty' => 'intermediate',
                'light' => 'bright-indirect',
                'water' => 'moderate',
                'temperature' => '16-26°C',
                'humidity' => '50-70%',
                'rooms' => ['living-room', 'office', 'balcony'],
                'quantity_categories' => ['single'],
                'fertilizer' => 'Bonsai food monthly during active growth.',
                'soil' => 'High quality akadama or organic bonsai potting mix.',
                'description' => 'Living sculpted art featuring a gnarled, exposed aerial root trunk with dense pads of glossy dark green miniature foliage.',
                'price' => 2500.00,
                'stock' => 12,
                'image' => '/images/jade.jpg',
                'is_active' => true,
                'views' => 580,
                'total_sold' => 15,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Trailing String of Pearls',
                'scientific_name' => 'Curio rowleyanus',
                'category' => 'Succulents',
                'size' => 'Small',
                'difficulty' => 'intermediate',
                'light' => 'direct-sun',
                'water' => 'low',
                'temperature' => '15-28°C',
                'humidity' => '30-50%',
                'rooms' => ['balcony', 'living-room', 'kitchen'],
                'quantity_categories' => ['single', 'hanging-basket'],
                'fertilizer' => 'Diluted succulent fertilizer once in spring.',
                'soil' => 'Fast-draining gritty succulent soil.',
                'description' => 'Fascinating trailing succulent strands adorned with emerald sphere bead pearls that cascade gracefully over shelf rims and hanging pots.',
                'price' => 680.00,
                'stock' => 25,
                'image' => '/images/pothos.jpg',
                'is_active' => true,
                'views' => 450,
                'total_sold' => 23,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],

            // Accessories
            [
                'name' => 'Minimalist Ceramic Planter with Saucer',
                'scientific_name' => null,
                'category' => 'Pots',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['living-room', 'office'],
                'quantity_categories' => ['single'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'High-fired ceramic planter with matte glazed finish and bottom drainage hole with matching saucer.',
                'price' => 650.00,
                'stock' => 45,
                'image' => '/images/pot1.jpg',
                'is_active' => true,
                'views' => 180,
                'total_sold' => 15,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Handcrafted Terracotta Clay Pot',
                'scientific_name' => null,
                'category' => 'Pots',
                'size' => 'Large',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['balcony', 'living-room'],
                'quantity_categories' => ['single'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'Breathable natural clay pot crafted by local artisans. Prevents root rot naturally by absorbing excess soil moisture.',
                'price' => 850.00,
                'stock' => 30,
                'image' => '/images/pot2.jpg',
                'is_active' => true,
                'views' => 220,
                'total_sold' => 20,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
            [
                'name' => 'Modern Matte Sage Green Planter',
                'scientific_name' => null,
                'category' => 'Pots',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['living-room', 'bedroom'],
                'quantity_categories' => ['single'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'Contemporary sage green finish with smooth cylindrical profile. Ideal for monsteras and philodendrons.',
                'price' => 950.00,
                'stock' => 25,
                'image' => '/images/pot3.webp',
                'is_active' => true,
                'views' => 195,
                'total_sold' => 18,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Textured Fluted Nordic Pot',
                'scientific_name' => null,
                'category' => 'Pots',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['living-room', 'office'],
                'quantity_categories' => ['single'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'Elegant vertical fluted design adding tactile depth and modern Scandinavian style to tabletops and desks.',
                'price' => 1150.00,
                'stock' => 20,
                'image' => '/images/pot4.jpg',
                'is_active' => true,
                'views' => 140,
                'total_sold' => 12,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Long-Spout Precision Watering Can 1.5L',
                'scientific_name' => null,
                'category' => 'Tools',
                'size' => 'Medium',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['balcony', 'kitchen'],
                'quantity_categories' => ['single'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'Stainless steel long slender spout allows targeted watering right at the soil surface without splashing foliage.',
                'price' => 1250.00,
                'stock' => 35,
                'image' => '/images/can.jpg',
                'is_active' => true,
                'views' => 260,
                'total_sold' => 24,
                'is_popular_item' => true,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Ergonomic Soil Trowel & Shovel',
                'scientific_name' => null,
                'category' => 'Tools',
                'size' => 'Small',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['balcony'],
                'quantity_categories' => ['single'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'Rust-resistant heavy-duty gardening trowel with comfortable rubber grip for easy repotting and aerating.',
                'price' => 550.00,
                'stock' => 50,
                'image' => '/images/sovel.webp',
                'is_active' => true,
                'views' => 170,
                'total_sold' => 30,
                'is_popular_item' => false,
                'is_best_seller' => false,
            ],
            [
                'name' => 'Chunky Aroid & Tropical Soil Mix 5L',
                'scientific_name' => null,
                'category' => 'Soil',
                'size' => 'Large',
                'difficulty' => 'beginner',
                'light' => null,
                'water' => null,
                'temperature' => null,
                'humidity' => null,
                'rooms' => ['balcony'],
                'quantity_categories' => ['single', 'pack-of-2'],
                'fertilizer' => null,
                'soil' => null,
                'description' => 'Custom blended orchid bark, coarse perlite, charcoal, and coco coir. The ultimate anti-root-rot formula for Kathmandu homes.',
                'price' => 450.00,
                'stock' => 80,
                'image' => '/images/best-soil-for-indoor-plants-1000x667-62c2fde2d71ae_n.webp',
                'is_active' => true,
                'views' => 320,
                'total_sold' => 60,
                'is_popular_item' => true,
                'is_best_seller' => true,
            ],
        ];

        foreach ($plants as $item) {
            Plant::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }

        // Seed sample orders for admin dashboard & reporting
        $user = User::where('role', '!=', 'admin')->first() ?? User::first();
        if ($user) {
            $monstera = Plant::where('name', 'Monstera Deliciosa')->first();
            $snake = Plant::where('name', 'Snake Plant Laurentii')->first();
            $pot = Plant::where('name', 'Minimalist Ceramic Planter with Saucer')->first();
            $soil = Plant::where('name', 'Chunky Aroid & Tropical Soil Mix 5L')->first();

            $orders = [
                [
                    'tracking_number' => 'TRK-2026-8801',
                    'user_id' => $user->id,
                    'subtotal' => 2100.00,
                    'delivery_fee' => 200.00,
                    'tax' => 0.00,
                    'total' => 2300.00,
                    'status' => 'delivered',
                    'payment_status' => 'paid',
                    'shipping_name' => 'Bikash Thapa',
                    'shipping_phone' => '+977-9841234567',
                    'shipping_city' => 'Lalitpur',
                    'shipping_address' => 'Jhamsikhel, Lalitpur, Nepal',
                    'created_at' => now()->subDays(5),
                ],
                [
                    'tracking_number' => 'TRK-2026-8802',
                    'user_id' => $user->id,
                    'subtotal' => 1350.00,
                    'delivery_fee' => 100.00,
                    'tax' => 0.00,
                    'total' => 1450.00,
                    'status' => 'shipped',
                    'payment_status' => 'pending',
                    'shipping_name' => 'Aayush Shrestha',
                    'shipping_phone' => '+977-9851098765',
                    'shipping_city' => 'Kathmandu',
                    'shipping_address' => 'Baluwatar, Kathmandu, Nepal',
                    'created_at' => now()->subDays(3),
                ],
                [
                    'tracking_number' => 'TRK-2026-8803',
                    'user_id' => $user->id,
                    'subtotal' => 2900.00,
                    'delivery_fee' => 200.00,
                    'tax' => 0.00,
                    'total' => 3100.00,
                    'status' => 'processing',
                    'payment_status' => 'paid',
                    'shipping_name' => 'Priya Adhikari',
                    'shipping_phone' => '+977-9801122334',
                    'shipping_city' => 'Kathmandu',
                    'shipping_address' => 'New Baneshwor, Kathmandu, Nepal',
                    'created_at' => now()->subDays(1),
                ],
                [
                    'tracking_number' => 'TRK-2026-8804',
                    'user_id' => $user->id,
                    'subtotal' => 750.00,
                    'delivery_fee' => 100.00,
                    'tax' => 0.00,
                    'total' => 850.00,
                    'status' => 'pending',
                    'payment_status' => 'pending',
                    'shipping_name' => 'Suman Tamang',
                    'shipping_phone' => '+977-9861998877',
                    'shipping_city' => 'Bhaktapur',
                    'shipping_address' => 'Suryabinayak, Bhaktapur, Nepal',
                    'created_at' => now()->subHours(6),
                ],
            ];

            foreach ($orders as $orderData) {
                $order = Order::updateOrCreate(
                    ['tracking_number' => $orderData['tracking_number']],
                    $orderData
                );

                if ($monstera && $order->wasRecentlyCreated) {
                    OrderItem::create([
                        'order_id' => $order->id,
                        'plant_id' => $monstera->id,
                        'quantity' => 1,
                        'price' => $monstera->price,
                        'line_total' => $monstera->price,
                    ]);
                }
                if ($snake && $order->wasRecentlyCreated) {
                    OrderItem::create([
                        'order_id' => $order->id,
                        'plant_id' => $snake->id,
                        'quantity' => 1,
                        'price' => $snake->price,
                        'line_total' => $snake->price,
                    ]);
                }
            }
        }
    }
}
